language: haskell

ghc:
  - 7.8

services:
  - riak

before_script:
  - "curl http://apt.basho.com/gpg/basho.apt.key | sudo apt-key add -"
  - 'sudo bash -c "echo deb http://apt.basho.com $(lsb_release -sc) main > /etc/apt/sources.list.d/basho.list"'
  - "sudo apt-get update"
  - "yes n | sudo apt-get install riak"
  - "sudo service riak start"
  # - ! 'echo "root: .riaktest" > spec/support/test_server.yml'
  # - ! 'echo "source: /usr/sbin" >> spec/support/test_server.yml'
  - "ulimit -n 2048"
  - "riak version"

install:
  - export CABAL=cabal
  - $CABAL sandbox init
  - cd protobuf && $CABAL sandbox init && $CABAL install && cd ..
  - $CABAL install --dependencies-only --enable-tests
  - $CABAL configure -flib-Werror --enable-tests

script:
  - $CABAL build
  - $CABAL test --show-details=always
  # - scripts/stats
