language: c
sudo: false

git:
  submodules: true  # whether to recursively clone submodules

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.mafia

before_script:
 # riak
 - RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.2/2.2.0/ubuntu/trusty/riak_2.2.0-1_amd64.deb
 - sudo ./tools/travis-ci/riak-install -d "$RIAK_DOWNLOAD_URL"
 - sudo ./tools/setup-riak

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx

matrix:
  include:
    - compiler: "ghc-7.10.3"
      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-1.24,ghc-7.10.3], sources: [hvr-ghc]}}
    - compiler: "ghc-8.0.2"
      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
    - compiler: "ghc-8.2.2"
      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.0,ghc-8.2.2], sources: [hvr-ghc]}}
    - compiler: "ghc-8.4.4"
      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.0,ghc-8.4.4], sources: [hvr-ghc]}}

before_install:
 - unset CC
 - PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$PATH

script:
 # time it out before travis kills it.
  # If travis times out the build, it wont save the cache, meaning the
  # next build will also most likely timeout
  # (travis_wait doesnt work btw, theres still a global timeout of
  # approx 40 mins it seems.
  - timeout 35m bin/ci

deploy:
  skip_cleanup: true
  provider: hackage
  username: $HACKAGE_USERNAME
  password: $HACKAGE_PASSWORD
  on:
    repo: riak-haskell-client/riak-haskell-client
    tags: true
