language: c
sudo: required
dist: trusty

# services:
#   - riak

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - ulimit -n 4096
  # riak
  - sudo apt-get -y install build-essential libc6-dev-i386 git
  - sudo apt-get -y install erlang-nox erlang-dev erlang-reltool
  - RIAK_STRIP_V=$(echo $RIAK | sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2/')
  - wget http://s3.amazonaws.com/downloads.basho.com/riak/$RIAK_STRIP_V/$RIAK/riak-$RIAK.tar.gz
  - tar zxvf riak-$RIAK.tar.gz
  - cd riak-$RIAK
  - make rel
  - sed -r --in-place -e 's/^(search) = .*/\1 = on/' rel/riak/etc/riak.conf
  - ./rel/riak/bin/riak start
  - ./rel/riak/bin/riak ping
  - ./rel/riak/bin/riak-admin wait-for-service riak_kv
  - ./rel/riak/bin/riak-admin wait-for-service yokozuna
  # CRDTs
  - ./rel/riak/bin/riak-admin bucket-type create maps '{"props":{"datatype":"map"}}'
  - ./rel/riak/bin/riak-admin bucket-type create sets '{"props":{"datatype":"set"}}'
  - ./rel/riak/bin/riak-admin bucket-type create counters '{"props":{"datatype":"counter"}}'
  - ./rel/riak/bin/riak-admin bucket-type activate maps
  - ./rel/riak/bin/riak-admin bucket-type activate sets
  - ./rel/riak/bin/riak-admin bucket-type activate counters
  # plain bucket-types
  - ./rel/riak/bin/riak-admin bucket-type create untyped-1 '{"props":{}}'
  - ./rel/riak/bin/riak-admin bucket-type create untyped-2 '{"props":{}}'
  - ./rel/riak/bin/riak-admin bucket-type activate untyped-1
  - ./rel/riak/bin/riak-admin bucket-type activate untyped-2
  # +search
  - curl -XPUT 127.0.0.1:8098/search/index/set-ix -H 'Content-Type:application/json' -d '{"schema":"_yz_default"}'
  - ./rel/riak/bin/riak-admin bucket-type update sets '{"props":{"search_index":"set-ix"}}'
  - cd -

matrix:
  include:
    - env: GHCVER=7.8.4 ARGS="--stack-yaml=.stack-7.8.4.yaml" RIAK=2.1.3
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.8.4 ARGS="--stack-yaml=.stack-7.8.4.yaml" RIAK=2.0.6
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}

    - env: GHCVER=7.10.3 ARGS="--stack-yaml=.stack-7.10.3.yaml" RIAK=2.1.3
      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}
    - env: GHCVER=7.10.3 ARGS="--stack-yaml=.stack-7.10.3.yaml" RIAK=2.0.6
      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}

    - env: GHCVER=8.0.1 ARGS="" RIAK=2.1.3
      addons: {apt: {packages: [ghc-8.0.1],sources: [hvr-ghc]}}
    - env: GHCVER=8.0.1 ARGS="" RIAK=2.0.6
      addons: {apt: {packages: [ghc-8.0.1],sources: [hvr-ghc]}}

    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.1.3
      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}
    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.0.6
      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

  allow_failures:
    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.1.3
    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.0.6

install:
  - stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script:
  - stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
